name: Update Image Readme Dark

on:
  workflow_dispatch:
  schedule:
    # Runs every 6 hours
    - cron: "0 */6 * * *"

jobs:
  update-readme:
    name: Update Readme Image Dark
    runs-on: ubuntu-latest
    steps:
      - uses: thisissakshi/update-readme-image@dark
        with:
          IMG_ALT: Just some gif
          IMG_PATH: .github/images/dark_mode
          ALIGN: center
          HEIGHT: 55%
          WIDTH: 55%
          COMMIT_MESSAGE: Updated Dark mode gif
