name: Update Image Readme Light

on:
  workflow_dispatch:
  schedule:
    # Runs at 5:30 UTC everyday
    - cron: "30 5 * * *"

jobs:
  update-readme:
    name: Update Image README
    runs-on: ubuntu-latest
    steps:
      - uses: siddharth2016/update-readme-image@main
        with:
          IMG_ALT: Just some gif
          IMG_PATH: ThisisSakshi/.github/images/light_mode
          ALIGN: center
          WIDTH: 45%
          COMMIT_MESSAGE: Updated Light mode gif