name: Update Image Readme Dark

on:
  workflow_dispatch:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"

jobs:
  update-readme:
    name: Update Readme Image Dark
    runs-on: ubuntu-latest
    steps:
      - uses: thisissakshi/update-readme-image@dark
        with:
          IMG_ALT: Just some gif
          IMG_PATH: .github/images/dark_mode
          ALIGN: center
          HEIGHT: 46%
          WIDTH: 46%
          COMMIT_MESSAGE: Updated Dark mode gif
