name: Update Image Readme Light

on:
  workflow_dispatch:
  schedule:
    # Runs every 6 hours past 2 minutes
    - cron: "5 * * * *"

jobs:
  update-readme:
    name: Update Readme Image Light
    runs-on: ubuntu-latest
    steps:
      - uses: thisissakshi/update-readme-image@light
        with:
          IMG_ALT: Just some gif
          IMG_PATH: .github/images/light_mode
          ALIGN: center
          HEIGHT: 55%
          WIDTH: 55%
          COMMIT_MESSAGE: Updated light mode gif
