name: Update Image Readme Light

on:
  workflow_dispatch:
  schedule:
    # Runs every 12 hours past 2 minutes
    - cron: "2 */12 * * *"

jobs:
  update-readme:
    name: Update Readme Image Light
    runs-on: ubuntu-latest
    steps:
      - uses: thisissakshi/update-readme-image@light
        with:
          IMG_ALT: Just some gif
          IMG_PATH: .github/images/light_mode
          ALIGN: center
          HEIGHT: 46%
          WIDTH: 46%
          COMMIT_MESSAGE: Updated light mode gif
