name: Update Image Readme Dark

on:
  workflow_dispatch:
  schedule:
    # Runs at 5:30 UTC everyday
    - cron: "25 22 * * *"

jobs:
  update-readme:
    name: Update Image README
    runs-on: ubuntu-latest
    steps:
      - uses: thisissakshi/update-readme-image@main
        with:
          IMG_ALT: Just some gif
          IMG_PATH: .github/images/dark_mode
          ALIGN: center
          HEIGHT: 180px
          WIDTH: ''
          COMMIT_MESSAGE: Updated Dark mode gif
